enlistment_system/config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :students
  devise_for :views
  devise_for :users
  devise_scope :user do
    authenticated :user do
      resources :students
      resources :assessments
        resources :class_catalogs
        resources :packages
        resources :students do
          resources :payments
        end
        resources :periods
        resources :assessments
        get "/dashboard", to: "pages#index"

      root to: "pages#index"
    end

    unauthenticated :user do
      get "/assessments/index.html.erb", to: "assessments#index", as: "index"
      root to: "creatives#index"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  


end

enlistment_system/app/models/period.rb
class Period < ApplicationRecord

has_many :class_catalogs
has_many :assessments
    accepts_nested_attributes_for :assessments

end

enlistment_system/app/controllers/periods_controller.rb
  class PeriodsController < ApplicationController
    before_action :set_period, only: [:show, :edit, :update, :destroy]

    # GET /periods
    # GET /periods.json
    def index
      @periods = Period.all
      render "periods/index.html.erb"
    end

    # GET /periods/1
    # GET /periods/1.json
    def show
      @period = Period.find(params[:id])
      render "periods/show.html.erb"
    end

    # GET /periods/new
    def new
      @period = Period.new
      render "periods/new.html.erb"
    end

    # GET /periods/1/edit
    def edit
      @period = Period.find(params[:id])
      render "periods/edit.html.erb"
    end

    # POST /periods
    # POST /periods.json
    def create
      @period = Period.new(period_params)
      respond_to do |format|
        if @period.save
          format.html { redirect_to period_path(@period.id), notice: 'Period was successfully created.' }
          format.json { render :show, status: :created, location: @period }
        else
          format.html { render :new }
          format.json { render json: @period.errors, status: :unprocessable_entity }
          render "periods/new.html.erb"
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_period
        @period = Period.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def period_params
        params.require(:period).permit!
        # params.fetch(:period, {})
      end

end

enlistment_system/app/helpers/periods_helper.rb
module PeriodsHelper
end

enlistment_system/app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    Period Start: <%= f.date_select :period_start %>
    <br>
    Period End: <%= f.date_select :period_end %>
    <br>
    <%= f.submit %>
  </div>
<% end %>

enlistment_system/app/views/periods/edit.html.erb
<body style="background-color: #e8e8e8;">
<h1 style="background-color: #0374b5; color: #ffffff; margin: 0px; padding: 0px; text-align: center;"><b>Editing Period</b></h1>

<br><br><div style="text-align:center; font-family: Helvetica Neue, Helvetica, Arial; font-size: 20px; border: 5px solid #0374b5; width: 500px;height: 120px; position: absolute;left: 420px; top: 150px;padding-top: 10px;"><%= render 'form', period: @period %></div>

<button class="btn btn-default" style="position: absolute;  bottom: 300px; right: 600px; color: #ffffff;"><%= link_to 'Show', period_path(:period_id) %> </button>
<button class="btn btn-default" style="position: absolute;  bottom: 300px; right: 700px; color: #ffffff;"><%= link_to 'Back', periods_path %></button>

</body>

enlistment_system/app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<h2 style="text-align: center;">Periods</h1>

<table>
  <thead>
    <tr>
      Period Start
    </tr>
    <tr>
      Period End
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <%= period.period_start %>
        <%= period.period_end %>
      </tr>
      <tr>
        <td><button class="btn btn-success"><%= link_to 'Show', period_path(period) %></td></button>
        <td><button class="btn btn-warning"><%= link_to 'Edit', edit_period_path(period) %></td></button>
        <td><button class="btn btn-danger"><%= link_to 'Destroy', period_path(period), method: :delete, data: { confirm: 'Are you sure?' } %></td></button>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Period', new_period_path %>

enlistment_system/app/views/periods/new.html.erb
<body style="background-color: #e8e8e8;">

<h1 style="background-color: #0374b5; color: #ffffff; margin: 0px; padding: 0px; text-align: center;"><b>New Period</b></h1>

<br><br><div style="text-align:center; font-family: Helvetica Neue, Helvetica, Arial; font-size: 20px; border: 5px solid #0374b5; width: 500px;height: 120px; position: absolute;left: 420px; top: 150px;padding-top: 10px;"><%= render 'form', period: @period %></div>

<button class="btn btn-info" style="position: absolute;  bottom: 300px; right: 650px; color: #ffffff;"><%= link_to 'Back', periods_path %></button>

</body>

enlistment_system/app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>