enlistment_system/config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :students
  devise_for :views
  devise_for :users
  devise_scope :user do
    authenticated :user do
      resources :students
      resources :assessments
        resources :class_catalogs
        resources :packages
        resources :students do
          resources :payments
        end
        resources :periods
        resources :assessments
        get "/dashboard", to: "pages#index"

      root to: "pages#index"
    end

    unauthenticated :user do
      get "/assessments/index.html.erb", to: "assessments#index", as: "index"
      root to: "creatives#index"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  


end

enlistment_system/app/models/payment.rb
class Payment < ApplicationRecord
    # validates_length_of :number_of_installment, :minimum => 1, :maximum => 1, presence: true
    
    belongs_to :assessment

    
    belongs_to :student
end

enlistment_system/app/controllers/payments_controller.rb
  class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
    @payments = student.payments
    student = Student.find(params[:student_id])
    
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    student = Student.find(params[:student_id])
    @payment = student.payments.find(params[:id])
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @payment.assessment = Student.find(params[:student_id]).assessment
  end

  # GET /payments/1/edit
  def edit
    student = Student.find(params[:student_id])
    @payment = student.payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    # student = Student.find(params[:student_id])
    # @payment = student.payments.create(params[:payment])
    # @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    student = Student.find(params[:student_id])
    @payment = student.payments.find(params[:id])
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    student = Student.find(params[:student_id])
    #2nd you retrieve the comment thanks to params[:id]
    @payment = student.payments.find(params[:id])

    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit!
    end
end

enlistment_system/app/helpers/payments_helper.rb
module PaymentsHelper
end

enlistment_system/app/views/payments/_form.html.erb
<%= simple_form_for([@payment.student, @payment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amount_paid %>
    <%= f.association :assessment, as: :hidden %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

  





<% end %>

enlistment_system/app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', [@payment .student, @payment] %> |
<%= link_to 'Back', student_payments_path(@payment.student) %>

enlistment_system/app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>Assessment ID</th>
      <th>Amount Paid</th>
      <th>Paid on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.assessment_id %></td>
        <td><%= payment.amount_paid %></td>
        <td><%= payment.created_on %></td>
        <td><%= link_to 'Show', [payment.student, payment] %></td>
        <td><%= link_to 'Edit', edit_student_payment_path(payment.post, payment) %></td>
        <td><%= link_to 'Destroy', [payment.post, payment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_student_payment_path %>

enlistment_system/app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', student_payments_path(:student_id) %>

enlistment_system/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assessment_ID</strong>
  <%= @payment.assessment_id %>
</p>

<p>
  <strong>Amount Paid</strong>
  <%= @payment.amount_paid %>
</p>

<p>
  <strong>Created At</strong>
  <%= @payment.created_at %>
</p>

<%= link_to 'Edit', edit_student_payment_path(@payment,student, @payment) %> |
<%= link_to 'Back', student_payments_path(@payment.student) %>